name: secure-file-share

services:
  database:
    container_name: sfs-pg
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      # seeding
      # - ./backend/database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # named volume
      - sfs-data:/var/lib/postgresql/data
volumes:
  sfs-data:
    external: true
